services:
- type: web
  name: drinkbot-go
  env: go
  repo: https://github.com/Rebeccasun31/line-bot-go-on-render.git
  buildCommand: cd code; go build -o app
  startCommand: ./code/app
  plan: free
  autoDeploy: true
  envVars:
  - key: LINE_CHANNEL_TOKEN
    sync: false
  - key: LINE_CHANNEL_SECRET
    sync: false